[variables]
NODE_ENV = 'production'

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run build", "node ./other/sentry-create-release"]

[start]
cmd = "bun start"