// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type Insert_registrationArgs = {
  readonly "registrationNote"?: string | null;
  readonly "fullname": string;
  readonly "nickname": string;
  readonly "birthDate": Date;
  readonly "birthPlace": string;
  readonly "gender": string;
  readonly "nisn"?: string | null;
  readonly "previousSchool"?: string | null;
  readonly "province": string;
  readonly "cityOrRegency": string;
  readonly "district": string;
  readonly "village": string;
  readonly "postalCode": string;
  readonly "street": string;
  readonly "houseNumber": string;
  readonly "addressDescription"?: string | null;
  readonly "motherFullname": string;
  readonly "motherPhone": string;
  readonly "motherEmail": string;
  readonly "fatherFullname": string;
  readonly "fatherPhone": string;
  readonly "fatherEmail": string;
  readonly "grade": number;
  readonly "valueCenterId": string;
  readonly "academicYearId": string;
};

export type Insert_registrationReturns = {
  "id": string;
};

export function insert_registration(client: Executor, args: Insert_registrationArgs): Promise<Insert_registrationReturns> {
  return client.queryRequiredSingle(`\
insert Registration {
    registration_date := datetime_of_statement(),
    registration_note := <optional str>$registrationNote,
    fullname := <str>$fullname,
    nickname := <str>$nickname,
    birth_date := <datetime>$birthDate,
    birth_place := <str>$birthPlace,
    gender := <str>$gender,
    nisn := <optional str>$nisn,
    previous_school := <optional str>$previousSchool,
    province := <str>$province,
    city_or_regency := <str>$cityOrRegency,
    district := <str>$district,
    village := <str>$village,
    postal_code := <str>$postalCode,
    street := <str>$street,
    house_number := <str>$houseNumber,
    address_description := <optional str>$addressDescription,
    mother_fullname := <str>$motherFullname,
    mother_phone := <str>$motherPhone,
    mother_email := <str>$motherEmail, 
    father_fullname := <str>$fatherFullname, 
    father_phone := <str>$fatherPhone, 
    father_email := <str>$fatherEmail,
    grade := <int64>$grade,
    ValueCenter := (
        select ValueCenter
        filter .id = <uuid>$valueCenterId
    ),
    AcademicYear := (
        select AcademicYear
        filter .id = <uuid>$academicYearId
    ),
}`, args);

}
